import { test, expect } from '@playwright/test';

test('App install', async ({ page }) => {
  await page.goto('https://accounts.shopify.com/lookup?rid=cfe60a05-34ef-4273-99ee-4f0737268471&verify=1743932538-6hxM7cnRn715SF1SaDwjxOC9n9a0p3820p3n9B%2BaWjY%3D');
  await page.getByRole('textbox', { name: 'Email' }).fill('naveen94.gotur@gmail.com');
  await page.getByRole('button', { name: 'Continue with email' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@1234');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByRole('button', { name: 'Apps' }).click();
  await page.getByRole('option', { name: 'All recommended apps' }).click();
  await page.locator('div:nth-child(2) > div > ._flexColumnContainer_1uo3o_1').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Shopify Search & Discovery' }).click();
  const page1 = await page1Promise;
  await page1.goto('https://apps.shopify.com/search-and-discovery?st_campaign=app-card-6bac79c21731e1e8e59b127c6213010a&st_source=admin-web&utm_campaign=app-card-6bac79c21731e1e8e59b127c6213010a&utm_source=shopify');
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('button', { name: 'Install', exact: true }).click();
  const page2 = await page2Promise;
  await page2.getByRole('heading', { name: 'Search & Discovery' }).getByRole('link').click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().locator('div').filter({ hasText: /^Customize filters$/ }).getByRole('link').click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('link', { name: 'Edit Availability' }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('textbox', { name: 'Filter label' }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('textbox', { name: 'Filter label' }).fill('Availability1');
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('button', { name: 'Save' }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('link', { name: 'Filters', exact: true }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('cell', { name: 'Edit Price', exact: true }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('textbox', { name: 'Filter label' }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('textbox', { name: 'Filter label' }).fill('100');
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('button', { name: 'Save' }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('link', { name: 'Filters', exact: true }).click();
  const page3Promise = page2.waitForEvent('popup');
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('link', { name: 'View' }).click();
  const page3 = await page3Promise;
  await page3.getByText('My Store Enter using password').click();
  await page3.getByRole('textbox', { name: 'Email' }).click();
  await page3.getByRole('textbox', { name: 'Email' }).fill('naveen94.gotur@gmail.com');
  await page3.getByRole('button', { name: 'Subscribe' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Challenge Image 5' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Challenge Image 6' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Challenge Image 4' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Verify Answers' }).click();
  await page3.locator('iframe[title="Widget containing checkbox for hCaptcha security challenge"]').contentFrame().locator('#anchor-tc').click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Challenge Image 4' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Next Challenge' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Challenge Image 1' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Challenge Image 3' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Challenge Image 8' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByRole('button', { name: 'Verify Answers' }).click();
  await page3.locator('iframe[title="Main content of the hCaptcha challenge"]').contentFrame().getByText('If there are None, click Skip').click();
  await page3.locator('div:nth-child(3) > div:nth-child(2)').first().click();
  await page2.getByLabel('Navigation', { exact: true }).getByRole('link', { name: 'Search & Discovery' }).click();
  await page2.getByRole('link', { name: 'Settings' }).first().click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('row', { name: 'Select Product recommendation Edit GiftCard No products No products' }).getByLabel('Select Product recommendation').check();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('row', { name: 'Select Product recommendation Edit Pen No products No products' }).getByLabel('Select Product recommendation').check();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('link', { name: 'Add recommendations' }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('textbox', { name: 'Search products' }).first().click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('button', { name: 'Browse' }).first().click();
  await page2.getByLabel('Select: GiftCard').click();
  await page2.getByLabel('Disabled: Pen').click();
  await page2.getByLabel('Disabled: Pen').click();
  await page2.getByRole('button', { name: 'Add' }).click();
  await page2.locator('iframe[name="app-iframe"]').contentFrame().getByRole('button', { name: 'Browse' }).first().click();
  await page2.getByLabel('Select: Pen').click();
  await page2.getByRole('button', { name: 'Add' }).click();
  await page2.getByRole('button', { name: 'Save' }).click();
  await page2.getByRole('button', { name: 'Naveen Gotur' }).click();
  await page2.getByRole('menuitem', { name: 'Log out' }).click();
});